name: CMake (Visual Studio)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4.1.7
        with:
          submodules: recursive

      - name: Configure CMake (x64)
        run: cmake --preset vs-x64

      - name: Build (x64)
        run: cmake --build --preset vs-x64-release --verbose

      - name: Configure CMake (x32)
        run: cmake --preset vs-x32

      - name: Build (x32)
        run: cmake --build --preset vs-x32-release --verbose
