name: CMake (Ninja)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4.1.7
        with:
          submodules: recursive

      - name: Install ninja-build tool
        uses: seanmiddleditch/gha-setup-ninja@v5

      - name: Configure build for amd64
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64

      - name: Configure CMake (x64)
        run: cmake --preset ninja-x64

      - name: Build (x64)
        run: cmake --build --preset ninja-x64-release --verbose

      - name: Build RelWithDebInfo (x64)
        run: cmake --build --preset ninja-x64-relwithdebinfo --verbose

      - name: Configure build for x86
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64_x86

      - name: Configure CMake (x86)
        run: cmake --preset ninja-x86

      - name: Build (x86)
        run: cmake --build --preset ninja-x86-release --verbose

      - name: Build RelWithDebInfo (x86)
        run: cmake --build --preset ninja-x86-relwithdebinfo --verbose

      - name: Prepare Web Listing
        run: md www

      - name: Copy Binaries (x64)
        run: copy build\Release\*.addon64 www\

      - name: Copy Binaries (x86)
        run: copy build32\Release\*.addon32 www\

      - name: Copy Binaries (Tools)
        run: copy build\Release\*.exe www\

      - name: Prepare Debug Web Listing
        run: md www\debug

      - name: Copy RelWithDebInfo Binaries (x64)
        run: copy build\RelWithDebInfo\*.addon64 www\debug\

      - name: Copy RelWithDebInfo Binaries (x86)
        run: copy build32\RelWithDebInfo\*.addon32 www\debug\

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "www"

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: windows-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
